export const experience = [
  {
    title: "Web Application Development Intern",
    company: "Lenovo Leap (AICTE)",
    period: "June 2026 – July 2026",
    location: "Remote",
    tech: ["Web Development", "AI-ML", "Full Stack"],
    bullets: [
      "Developed AI-driven web applications through hands-on projects and mentor-guided sessions.",
      "Applied full-stack and AI concepts to build real-world web applications.",
    ],
  },
  {
    title: "App Developer Intern",
    company: "CollegePaglu",
    period: "May 2026 – June",
    location: "Startup",
    tech: ["React-Native", "Firebase", "Android", ],
    bullets: [
      "Improved app UI/UX and added new features across the product.",
      "Developed and integrated new app features in a stipend-based internship environment.",
    ],
  },
  {
    title: "Tech Lead",
    company: "StylCop",
    period: "Feb 2026 – Present",
    location: "Startup",
    tech: ["Next.js", "TypeScript", "AI-ML", "Python"],
    bullets: [
      "Built StylCop, an AI-powered fashion platform for personalized outfit suggestions.",
      "Developed the landing page and working on the mobile app and social fashion features.",
    ],
  },
  {
    title: "Contributor",
    company: "Open Source Connect Global 2026",
    period: "Feb 2026",
    location: "Global (Remote)",
    tech: ["Git", "GitHub", "Full Stack Development"],
    bullets: [
      "Participated as an open-source contributor in a global collaborative development program.",
      "Contributed to project improvements, issue resolution, and feature development.",
    ],
  },
  {
    title: "Contributor",
    company: "Elite Coders — Winter of Code 2026 (ECWoC)",
    period: "Jan 2026 – Feb 2026",
    location: "India (Remote)",
    tech: ["Git", "GitHub", "Full Stack Development"],
    bullets: [
      "Contributed to open-source projects during ECWoC and secured 33rd rank nationally among participants.",
      "Collaborated on real-world development tasks, issue resolution, and feature improvements.",
    ],
  },
];

export const certifications = [
  { id: 1, path: "/images/icert.jpg", title: "Web Developer Intern", issuer: "Lenovo Leap" },
  { id: 2, path: "/images/cert7.jpeg", title: "Perf Workflow Challenge", issuer: "Perf" },
  { id: 3, path: "/images/cert1.jpg", title: "ECWoC Contributor", issuer: "Elite Coders — ECWoC 2026" },
  { id: 4, path: "/images/cert3.jpg", title: "Contributor", issuer: "Open Source Connect Global 2026" },
  { id: 5, path: "/images/cert2.png", title: "DBMS Course", issuer: "Scalar Topics" },
  { id: 6, path: "/images/cert.jpg", title: "Job Simulation", issuer: "Deloitte" },
];

export const skills: { name: string; icon: string; color: string }[] = [
  { name: "JavaScript", icon: "SiJavascript", color: "#F7DF1E" },
  { name: "TypeScript", icon: "SiTypescript", color: "#3178C6" },
  { name: "Python", icon: "SiPython", color: "#3776AB" },
  { name: "Java", icon: "FaJava", color: "#E76F00" },
  { name: "C/C++", icon: "SiCplusplus", color: "#00599C" },
  { name: "SQL", icon: "TbSql", color: "#4479A1" },
  { name: "HTML/CSS", icon: "SiHtml5", color: "#E34F26" },
  { name: "TailwindCSS", icon: "SiTailwindcss", color: "#06B6D4" },
  { name: "React", icon: "SiReact", color: "#61DAFB" },
  { name: "React Native", icon: "SiReact", color: "#61DAFB" },
  { name: "Next.js", icon: "SiNextdotjs", color: "#000000" },
  { name: "Expo", icon: "SiExpo", color: "#000000" },
  { name: "Node.js", icon: "SiNodedotjs", color: "#5FA04E" },
  { name: "Express.js", icon: "SiExpress", color: "#686868" },
  { name: "FastAPI", icon: "SiFastapi", color: "#009688" },
  { name: "MongoDB", icon: "SiMongodb", color: "#47A248" },
  { name: "PostgreSQL", icon: "SiPostgresql", color: "#4169E1" },
  { name: "Firebase", icon: "SiFirebase", color: "#FFCA28" },
  { name: "Cloudinary", icon: "SiCloudinary", color: "#3448C5" },
  { name: "AWS", icon: "SiAmazonwebservices", color: "#FF9900" },
  { name: "GCP", icon: "SiGooglecloud", color: "#4285F4" },
  { name: "NumPy", icon: "SiNumpy", color: "#4DABCF" },
  { name: "TensorFlow", icon: "SiTensorflow", color: "#FF6F00" },
  { name: "Git", icon: "SiGit", color: "#F05032" },
  { name: "Docker", icon: "SiDocker", color: "#2496ED" },
  { name: "Postman", icon: "SiPostman", color: "#FF6C37" },
  { name: "REST APIs", icon: "TbApi", color: "#009688" },
];

export const projects = [
  {
    id: 1,
    title: "MotionIt",
    description:
      "An advanced AI video generation platform that brings any image to life with realistic lip-synced talking videos.",
    tech: ["Next.js", "TypeScript", "AI-ML", "Python", "Cloudinary"],
    link: "https://motion-it.vercel.app/",
    github: "https://github.com/harshrana14-fi/MotionIt",
    category: "Full Stack",
    image: "/images/it.png",
    cover: "/cover7.jpg",
    status: "Building",
    featured: true,
  },
  {
    id: 2,
    title: "Vybe",
    description:
      "A code scanning and security tool specifically targeting the workflow of vibe coders.",
    tech: ["TypeScript", "DevTool", "CLI", "Groq"],
    link: "https://vybe-t1h3.vercel.app/",
    github: "https://github.com/harshrana14-fi/Vybe-",
    category: "Developer Tool",
    image: "/images/vybe.png",
    cover: "/c10.jpg",
    status: "Live",
    featured: true,
  },
  {
    id: 3,
    title: "Nyagrik",
    description:
      "Legal consultation platform providing information and services for citizens with document templates and guided workflows.",
    tech: ["React", "Next.js", "MongoDB", "TailwindCSS", "TypeScript"],
    link: "https://www.nyagrik.com/",
    github: "https://github.com/harshrana14-fi/nyagrik",
    category: "Full Stack",
    image: "/images/nyagrik.png",
    cover: "/cover8.jpg",
    status: "Startup Project",
    featured: false,
  },
  {
    id: 4,
    title: "StudHub",
    description:
      "An AI-powered academic toolkit for college students to simplify their academic journey.",
    tech: ["Next.js", "TypeScript", "MongoDB", "AI-ML", "Python"],
    link: "https://studtoolhub.vercel.app/",
    github: "https://github.com/harshrana14-fi/StudentHub",
    category: "Full Stack, AI-ML",
    image: "/images/studhub.png",
    cover: "/c2.jpg",
    status: "Live",
    featured: false,
  },
  {
    id: 5,
    title: "MedRag",
    description:
      "A RAG-based AI system that delivers accurate, natural language answers from complex health insurance policies with source citations.",
    tech: ["Next.js", "RAG", "ChromaDB", "Python"],
    link: "https://medrag-henna.vercel.app/",
    github: "https://github.com/harshrana14-fi/MEDRAG",
    category: "RAG Model",
    image: "/images/medrag.png",
    cover: "/c4.jpg",
    status: "Live",
    featured: true,
  },
  {
    id: 6,
    title: "StylMart",
    description:
      "A full-stack e-commerce platform built with Next.js featuring a unique modern minimalist design with aesthetic visual appeal.",
    tech: ["MongoDB", "Html5", "Css", "Javascript"],
    link: "https://stylmart-ecommplatform.onrender.com/",
    github: "https://github.com/harshrana14-fi/StylMart--EcommPlatform",
    category: "Web Dev",
    image: "/images/mart.png",
    cover: "/c1.jpg",
    status: "Live",
    featured: false,
  },
  {
    id: 7,
    title: "JARVIS",
    description:
      "Advanced AI Assistant using NLP and custom ML models to automate tasks and resolve natural language prompts.",
    tech: ["Next.js", "TypeScript", "MongoDB", "Python", "TensorFlow"],
    link: "https://jarvis-silk-six.vercel.app/",
    github: "https://github.com/harshrana14-fi/JARVIS",
    category: "Full Stack, AI-ML",
    image: "/images/jarvis.png",
    cover: "/c2.jpg",
    status: "Live",
    featured: false,
  },
  {
    id: 8,
    title: "WasteFlow",
    description:
      "AI-powered waste management platform connecting producers with recyclers using smart matching.",
    tech: ["Next.js", "MongoDB", "OpenAI", "Python"],
    link: "https://waste-flowipu.vercel.app/",
    github: "https://github.com/harshrana14-fi/WasteFlowipu",
    category: "AI/ML",
    image: "/images/wast.png",
    cover: "/c3.jpg",
    status: "Live",
    featured: false,
  },
];
